### ISSUE TITLE
Threshold reached on a large file with new thumbnail code

### ISSUE THREAD

**Issue by dietrichasuedu** [mother-db/ezEMLmotherDB#87]
![ScreenshotImageTooLarge_569MB](https://user-images.githubusercontent.com/10838163/235333497-6f620f4b-9492-4dde-af93-41466948e6cb.jpg)

Please see attached error for screenshot. This exception needs to be handled. Collaborators will be uploading large files. 300-400 MB files loaded fine but a 569 MB file reached a threshold with respect to the new thumbnail code. Students say that they previously had uploaded (before the new version on Friday, 4/28) a 600MB file with no issues.

**Comment by jpraymer** [comment]
Code was updated to handle large files. As opposed to depending on file resolution there is now an 8MB limit where any file larger than that will still upload but not generate a thumbnail. Due to large file sizes it may take a while for the server to generate a thumbnail if it is a few MB large but still under the limit. The limit can be changed if this turns out to be an issue.

**Comment by dietrichasuedu** [comment]
Thank you
